//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Database.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mAddTableHS {
            get {
                object obj = ResourceManager.GetObject("mAddTableHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently delete database &apos;{0}&apos; with all tables and datasets?.
        /// </summary>
        internal static string MB_AskDelete {
            get {
                return ResourceManager.GetString("MB_AskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete database ....
        /// </summary>
        internal static string MB_AskDeleteTitle {
            get {
                return ResourceManager.GetString("MB_AskDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mDatabase {
            get {
                object obj = ResourceManager.GetObject("mDatabase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mDatabase_readonly {
            get {
                object obj = ResourceManager.GetObject("mDatabase_readonly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mDataSet_TableView {
            get {
                object obj = ResourceManager.GetObject("mDataSet_TableView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mDeleteHS {
            get {
                object obj = ResourceManager.GetObject("mDeleteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        internal static string MySql_AddButton {
            get {
                return ResourceManager.GetString("MySql_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User:.
        /// </summary>
        internal static string MySql_CurrentUserLabel {
            get {
                return ResourceManager.GetString("MySql_CurrentUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below is a list of MySql databases currently installed on your MySql server. Note that this list only contains database entries, that was granted privilege to read for the current user..
        /// </summary>
        internal static string MySql_DatabaseBrowserLabel {
            get {
                return ResourceManager.GetString("MySql_DatabaseBrowserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySql Database Browser.
        /// </summary>
        internal static string MySql_DatabaseBrowserTitle {
            get {
                return ResourceManager.GetString("MySql_DatabaseBrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string MySql_EditButton {
            get {
                return ResourceManager.GetString("MySql_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name:.
        /// </summary>
        internal static string MySql_EditorDatabaseNameGroup {
            get {
                return ResourceManager.GetString("MySql_EditorDatabaseNameGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the new database:.
        /// </summary>
        internal static string MySql_EditorDatabaseNameLabel {
            get {
                return ResourceManager.GetString("MySql_EditorDatabaseNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use edited Schema.
        /// </summary>
        internal static string MySql_EditorDatabaseSchemaCheckBox {
            get {
                return ResourceManager.GetString("MySql_EditorDatabaseSchemaCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Schema:.
        /// </summary>
        internal static string MySql_EditorDatabaseSchemaGroup {
            get {
                return ResourceManager.GetString("MySql_EditorDatabaseSchemaGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract the database schema from the following template file:.
        /// </summary>
        internal static string MySql_EditorDatabaseSchemaLabel {
            get {
                return ResourceManager.GetString("MySql_EditorDatabaseSchemaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privileges for current user:.
        /// </summary>
        internal static string MySql_EditorPrivilegesLabel {
            get {
                return ResourceManager.GetString("MySql_EditorPrivilegesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new MySql Database.
        /// </summary>
        internal static string MySql_EditorTitle {
            get {
                return ResourceManager.GetString("MySql_EditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Databases found..
        /// </summary>
        internal static string MySql_NoItemsMessage {
            get {
                return ResourceManager.GetString("MySql_NoItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file containing SQL schema definitions:.
        /// </summary>
        internal static string MySql_OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("MySql_OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string MySql_PasswordLabel {
            get {
                return ResourceManager.GetString("MySql_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string MySql_RefreshButton {
            get {
                return ResourceManager.GetString("MySql_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        internal static string MySql_RemoveButton {
            get {
                return ResourceManager.GetString("MySql_RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string MySql_UsernameLabel {
            get {
                return ResourceManager.GetString("MySql_UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Odbc_DatabaseColumn {
            get {
                return ResourceManager.GetString("Odbc_DatabaseColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Odbc_DescriptionColumn {
            get {
                return ResourceManager.GetString("Odbc_DescriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        internal static string Odbc_DriverColumn {
            get {
                return ResourceManager.GetString("Odbc_DriverColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Sources:.
        /// </summary>
        internal static string Odbc_DsnSelectionGroup {
            get {
                return ResourceManager.GetString("Odbc_DsnSelectionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Data Sources.
        /// </summary>
        internal static string Odbc_ManageDsnTitle {
            get {
                return ResourceManager.GetString("Odbc_ManageDsnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Odbc_NameColumn {
            get {
                return ResourceManager.GetString("Odbc_NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Sources found..
        /// </summary>
        internal static string Odbc_NoItemsMesage {
            get {
                return ResourceManager.GetString("Odbc_NoItemsMesage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Odbc_PathColumn {
            get {
                return ResourceManager.GetString("Odbc_PathColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Odbc_ServerColumn {
            get {
                return ResourceManager.GetString("Odbc_ServerColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System DSN.
        /// </summary>
        internal static string Odbc_SystemDsnRadioText {
            get {
                return ResourceManager.GetString("Odbc_SystemDsnRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User DSN.
        /// </summary>
        internal static string Odbc_UserDsnRadioText {
            get {
                return ResourceManager.GetString("Odbc_UserDsnRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
    }
}
